In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic_train.csv')

In [3]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.shape()


TypeError: 'tuple' object is not callable

In [ ]:
df.shape

In [ ]:
df.isnull

In [ ]:
df.isnull()

In [ ]:
b = "saurab"+"shrestha"
print(b)

In [ ]:
b = "saurab"+" shrestha"
print(b)

In [ ]:
//ram krishna

In [ ]:
# //ram krishna

In [ ]:
list = [1,2,3,4,5,6,7]

In [ ]:
list[-1]

In [ ]:
list[0]

In [ ]:
list[:-1]

In [ ]:
list[::-1]

In [ ]:
(1,2,3,4)

In [ ]:
# tuple immutable

In [ ]:
dic = {'name':'saurab'}
print(dic)

In [ ]:
print(dic['name'])

In [ ]:
dict1 = {1:'ram', 2:'shyam', '3':'hari'}
dict1.keys()
dict1.values()

In [ ]:
print(dict1.keys(),
dict1.values())

In [ ]:
def function1():
    print("hello")
    
function1()

In [ ]:
def func2(arg):
    print(arg)

func2("hello guys this is from argument")

In [ ]:
ints = int(input("Enter a no guys \t"))

if ints % 2 == 0:
    print(f"{ints} is even")
    
else:
    print(f"{ints} is odd")

    

In [ ]:
print(f"sq of {ints} is {ints ** 2} .")

In [ ]:
print("sq of {ints} is {ints ** 2} .")

In [ ]:
class class1():
    def __init__(self):
        self.id = 1
        self.name = "Saurab"
    
    def show(self):
        print(self.id, self.name)
        
    def show_dami(self):
        print(f" Name:{self.name}")
        
ob1 = class1()
ob1.show_dami()
ob1.show()

        

In [ ]:
class class2(class1):
    def show_dami_id(self):
        print(f" ID:{self.id}")
        
ob2 = class2()
ob2.show_dami_id()
            
            

        

In [ ]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

x = Student("Mike", "Olsen", 2019)
print(x.graduationyear)

In [ ]:
# numpy
# module
def even_odd(n):
    """
    comment ho hai guys
    """
    
    if n % 2 ==0:
        print("even")
        
    else:
        print("odd")
        
        

In [ ]:
even_odd(55)

In [ ]:
from evenodd import even_odd as eo
# module load vayena vane kernel restart garne


In [ ]:
eo(4)

In [ ]:
# sudhan kadel
# ram acharya
# rabindra sapkota
# suraj 
# numpy kada ho hai guys


In [ ]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
# shift tab le documentation auxa
# tab le available methods haru dekhauxa
v = np.array([1,2,3,4])

In [ ]:
type(v)

In [ ]:
print(type(v))

In [ ]:
v


In [ ]:
zeros = np.zeros([5,5])

In [ ]:
print(zeros)

In [ ]:
zeros.shape

In [ ]:
zeros.reshape(1,25)


In [5]:
zeros.reshape(25,1)


NameError: name 'zeros' is not defined

In [6]:
len(zeros.reshape(25,1)
)

NameError: name 'zeros' is not defined

In [7]:
zeros.reshape(25,-1)
# row 25 ota column jati pani as idk


NameError: name 'zeros' is not defined

In [8]:
repeat = np.repeat(5,100)
repeat

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
a=repeat.reshape(10,10)
a.shape

(10, 10)

In [10]:
sum = np.sum(repeat,axis=0)
sum

500

In [11]:
list3 = [1,2,3,4,5]
# list3**2
arr2 = np.array(list3)
arr2**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [12]:
rand = np.random.randn(5,5)
# rand
rand.shape

(5, 5)

In [13]:
rant2 = np.random.randint(5,400,500)

In [14]:
rant2

array([ 55, 123, 162, 261, 320, 314, 226,  50, 353, 254, 159, 280, 179,
       390, 361, 157,  14,  79,  76,  26,  39,  40, 247,  23,  77, 390,
       293,  11, 248,  30, 282, 169, 192, 186, 348, 309, 229,   5, 231,
       378, 274,   6, 306, 369,  28, 359,  72, 330, 164, 344,  95, 337,
       146, 280, 215,  66, 221,  52, 143, 124, 172, 358, 106, 286, 286,
       131, 259,  95, 217, 160, 265, 203, 158, 108, 376, 122, 273, 314,
       140, 223, 208, 157,  97, 223, 262, 350, 294,  51, 316, 216,  65,
       327, 224, 208, 380, 249,  86, 246, 267, 161, 212,  25,  86, 163,
        59, 325, 337,  20, 193, 134, 334,  19,  75, 289,  54, 311, 391,
        69,  60, 119,  66, 174,  41, 268,  18,  97, 377, 364,  74, 106,
       353, 191,  48, 206,  78, 297, 140,  65, 189, 249, 136,  78, 352,
       321, 287,  18, 389, 336, 213, 356, 348, 271,  44, 384,  32, 256,
       249, 116, 317, 260, 368, 393, 158, 102, 325,  57, 150, 204, 261,
        13, 348,  86, 144, 365, 149, 150, 284,  21,  32, 332, 39

In [15]:
from collections import Counter

counts = Counter(rant2)

In [16]:
counts

Counter({55: 2,
         123: 2,
         162: 1,
         261: 3,
         320: 2,
         314: 6,
         226: 1,
         50: 3,
         353: 3,
         254: 1,
         159: 2,
         280: 2,
         179: 1,
         390: 2,
         361: 2,
         157: 2,
         14: 2,
         79: 2,
         76: 2,
         26: 3,
         39: 1,
         40: 3,
         247: 4,
         23: 1,
         77: 1,
         293: 1,
         11: 2,
         248: 1,
         30: 1,
         282: 4,
         169: 3,
         192: 3,
         186: 1,
         348: 4,
         309: 2,
         229: 2,
         5: 1,
         231: 3,
         378: 3,
         274: 1,
         6: 2,
         306: 1,
         369: 1,
         28: 1,
         359: 1,
         72: 2,
         330: 2,
         164: 3,
         344: 2,
         95: 2,
         337: 2,
         146: 4,
         215: 1,
         66: 4,
         221: 1,
         52: 3,
         143: 2,
         124: 1,
         172: 1,
         358: 1,
 

In [17]:
print(len(counts),len(rant2))


288 500


In [18]:
l1= []

l1.append(1)

In [19]:
l1

[1]

In [20]:
l2 = [1,2,3,[1,2]]
l2

[1, 2, 3, [1, 2]]

In [21]:
# tuple
# tuple immutable hai guys
t1 = (1,2,3)
t1

(1, 2, 3)

In [23]:
# dictionary
d1 = {}
d1[1] = 'Nepal'
d1[2] = 'India'
# d1
d1.values()



dict_values(['Nepal', 'India'])